language: node_js
node_js:
  - "6"
script: 
  - npm install
  - npm run lint
  - npm run test
cache:
  directories:
    - node_modules
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"